import { useState } from 'react';
import { Printer, Download, Mail } from 'lucide-react';
import { records, activeIssues, issueLabel, issueStatus, operational, elapsed, type Shift, type Handoff, shiftHistory, stationFor } from '../domain/model';
import { Field, StatusLabel, download, pumpNumber, type ViewProps } from './shared';
export function Records({model,engine,run,now}:ViewProps) {
 const live=operational(new Date(now));const [date,setDate]=useState(live.date);const [shift,setShift]=useState<Shift>(live.shift);const [report,setReport]=useState('hours');const [notes,setNotes]=useState('');const [mail,setMail]=useState(false);const [handoffId,setHandoffId]=useState('');
 const readings=records(model,'reading').filter(r=>r.date===date&&r.shift===shift).sort((a,b)=>(a.station??99)-(b.station??99));
 const issues=activeIssues(model).filter(e=>report==='spread'?stationFor(model,e.pumpId)!==null:['Down','Repairing','Spot check'].includes(issueStatus(e))); 
 const handoffs=records(model,'handoff').filter(h=>h.date===date&&h.shift===shift).sort((a,b)=>b.at-a.at);
 const handoff=handoffs.find(h=>h.id===handoffId)||handoffs[0];
 const events=shiftHistory(model,date,shift);
 const summary=`FLEET 1 · ${live.date} ${live.shift.toUpperCase()}\n\n${activeIssues(model).map(e=>`Pump ${pumpNumber(model,e.pumpId)} · ${issueStatus(e)} · ${issueLabel(e)} · ${elapsed(e,now)}${e.notes?` · ${e.notes}`:''}`).join('\n')||'No active issues.'}\n\n${notes}`;
 const exportCSV=()=>{const cell=(v:unknown)=>{const text=String(v??'');return `"${(/^[=+@-]/.test(text)?"'":'')+text.replaceAll('"','""')}"`;};download(`fleet-hours-${date}-${shift}.csv`,[['Station','Pump','Pump Hours','Deck Engine Hours','Notes','Entered by'],...readings.map(r=>[r.station??'Standby',pumpNumber(model,r.pumpId),r.pumpHours,r.deckHours,r.notes,r.actor])].map(row=>row.map(cell).join(',')).join('\n'),'text/csv');};
 return <><div className="page-heading"><div><h1>Records & handoff</h1><p>History, shift snapshots, and one report at a time.</p></div><button onClick={()=>download('fieldline-fleet-export.json',JSON.stringify(model,null,2))}><Download size={18}/>Export fleet data</button></div>
 <section className="surface handoff-composer"><div><h2>Hand the next shift a clear picture</h2><p>Captures the live {live.shift} shift · {live.date}, regardless of the report date below.</p></div><Field label="Outgoing shift notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What the incoming crew needs to know"/></Field><div className="button-row"><button className="primary" onClick={()=>run(()=>engine.submit({type:'handoff',notes}))}>Capture live handoff</button><button onClick={()=>{window.location.href=`mailto:?subject=${encodeURIComponent(`Fleet 1 handoff · ${live.date} ${live.shift}`)}&body=${encodeURIComponent(summary)}`;setMail(true);}}><Mail size={18}/>Open email draft</button></div>{mail&&<p role="status">Email draft opened in your mail app. No message was sent automatically.</p>}</section>
 <div className="toolbar"><Field label="Report"><select value={report} onChange={e=>setReport(e.target.value)}><option value="hours">Pump hours sheet</option><option value="down">Down equipment</option><option value="handoff">Shift handoff</option><option value="spread">Spread issues</option><option value="history">Shift history</option></select></Field><Field label="Operational date"><input type="date" value={date} onChange={e=>{setDate(e.target.value);setHandoffId('');}}/></Field><Field label="Shift"><select value={shift} onChange={e=>setShift(e.target.value as Shift)}><option value="day">Day</option><option value="night">Night</option></select></Field><button onClick={()=>window.print()}><Printer size={18}/>Print selected report</button>{report==='hours'&&<button onClick={exportCSV}><Download size={18}/>CSV</button>}</div>
 <article className="surface report-section"><h2>Fleet 1 · {report==='hours'?'Pump hours':report==='down'?'Down equipment':report==='handoff'?'Shift handoff':report==='spread'?'Spread issues':'Shift history'}</h2><p>{report==='down'||report==='spread'?`Currently unresolved · ${new Date(now).toLocaleString()}`:`${date} · ${shift} shift`}</p>
 {report==='hours'?<div className="table-scroll"><table><thead><tr>{['Station','Pump','Pump hours','Deck engine hours','Notes'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{readings.map(r=><tr key={r.id}><td>{r.station??'Standby'}</td><td>{pumpNumber(model,r.pumpId)}</td><td>{r.pumpHours??'—'}</td><td>{r.deckHours??'—'}</td><td>{r.notes}</td></tr>)}</tbody></table>{!readings.length&&<p>No readings for this sheet.</p>}</div>:report==='down'||report==='spread'?<div className="table-scroll"><table><thead><tr>{['Pump','Station','Status','Issue','Duration','Notes'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{issues.map(e=><tr key={e.id}><td>{pumpNumber(model,e.pumpId)}</td><td>{stationFor(model,e.pumpId)??'Standby'}</td><td>{issueStatus(e)}{e.watch?' + Watch':''}</td><td>{issueLabel(e)}</td><td>{elapsed(e,now)}</td><td>{e.notes}</td></tr>)}</tbody></table>{!issues.length&&<p>No abnormal equipment.</p>}</div>:report==='handoff'?<>{handoffs.length>1&&<Field label="Snapshot"><select value={handoff?.id} onChange={e=>setHandoffId(e.target.value)}>{handoffs.map(h=><option key={h.id} value={h.id}>{new Date(h.at).toLocaleTimeString()} · {h.actor}</option>)}</select></Field>}{handoff?<HandoffReport snapshot={handoff} model={model}/>:<p>No snapshot captured for this shift.</p>}</>:<ol className="timeline">{events.map(e=><li key={e.id}><strong>{e.kind==='reading'?`Pump ${pumpNumber(model,e.pumpId)} · meter readings`:e.kind==='issue'?`Pump ${pumpNumber(model,e.pumpId)} · ${e.component}`:e.kind==='movement'?`Pump ${pumpNumber(model,e.pumpId)} · ${e.action}`:e.kind==='service'?`Pump ${pumpNumber(model,e.pumpId)} · Completed ${e.type}`:e.kind==='audit'?`Audit · ${e.action}`:e.kind}</strong><p>{'notes'in e?e.notes:'reason'in e?e.reason:''}</p><small>{'actor'in e?e.actor:'createdBy'in e?e.createdBy:''}</small></li>)}</ol>}
 </article></>;
}
function HandoffReport({snapshot,model}:{snapshot:Handoff;model:ViewProps['model']}) {return <><p>Captured {new Date(snapshot.at).toLocaleString()} by {snapshot.actor}</p><p>{snapshot.notes||'No shift notes.'}</p><h3>Active issues & watches ({snapshot.issues.length})</h3>{snapshot.issues.map(e=><p key={e.id}><strong>Pump {pumpNumber(model,e.pumpId)}</strong> · {issueStatus(e)}{e.watch?' + Watch':''} · {issueLabel(e)} · {e.notes}</p>)}<h3>Completed repairs ({snapshot.repairs.length})</h3>{snapshot.repairs.map(e=><p key={e.id}>Pump {pumpNumber(model,e.pumpId)} · {e.component}</p>)}<h3>Pump swaps ({snapshot.swaps.length})</h3>{snapshot.swaps.map(e=><p key={e.id}>Pump {pumpNumber(model,e.pumpId)} → {e.replacement?pumpNumber(model,e.replacement):'Standby'} · {e.reason}</p>)}<h3>Lineup snapshot</h3><p>{snapshot.lineup.map(s=>`S${s.station}: ${s.pumpId?pumpNumber(model,s.pumpId):'Unassigned'}`).join(' · ')}</p></>;}
