import { useEffect, useState } from 'react';
import { Wrench, LayoutGrid, Clock3, ClipboardList, FileText, Settings, WifiOff, CloudCheck, AlertTriangle, X } from 'lucide-react';
import { Engine } from './data/engine';
import { storage } from './data/storage';
import { seed } from './data/seed';
import { configured, firebaseBackend, fleetId } from './data/firebase';
import { operational, type Model } from './domain/model';
import { Spread } from './ui/Spread';
import { Hours } from './ui/Hours';
import { Work } from './ui/Work';
import { Records } from './ui/Records';
import { PumpDrawer } from './ui/PumpDrawer';
import { Modal, Field, download } from './ui/shared';
const NAV=[{id:'spread',label:'Spread',icon:LayoutGrid},{id:'hours',label:'Hours',icon:Clock3},{id:'work',label:'Work',icon:ClipboardList},{id:'records',label:'Records',icon:FileText}] as const;
export default function App(){
 const [mode]=useState<'demo'|'firebase'>(()=>new URLSearchParams(location.search).get('mode')==='firebase'?'firebase':'demo');
 const [engine,setEngine]=useState<Engine|null>(null);const [version,setVersion]=useState(0);const [page,setPage]=useState<string>('spread');const [pumpId,setPumpId]=useState<string|null>(null);const [now,setNow]=useState(Date.now());const [settings,setSettings]=useState(false);const [error,setError]=useState('');const [actor,setActor]=useState('');
 useEffect(()=>{let alive=true;let cleanup=()=>{};try{const instance=new Engine(storage(`${mode}-${fleetId}`),mode,mode==='firebase'?firebaseBackend():undefined);const listener=()=>{if(alive)setVersion(v=>v+1);};instance.listeners.add(listener);setEngine(instance);instance.load(mode==='demo'?seed():{}).then(()=>{if(alive)setActor(instance.snapshot.actor);}).catch(e=>{if(alive)setError(e.message);});const refresh=()=>void instance.flush();const timer=setInterval(refresh,15000);window.addEventListener('online',refresh);window.addEventListener('offline',listener);const channel=new BroadcastChannel(`fieldline-${mode}-${fleetId}`);let receiving=false;channel.onmessage=()=>{instance.store.read().then(s=>{if(s){instance.snapshot=s;receiving=true;instance.notify();receiving=false;}});};const broadcast=()=>{if(!receiving)channel.postMessage('changed');};instance.listeners.add(broadcast);cleanup=()=>{clearInterval(timer);window.removeEventListener('online',refresh);window.removeEventListener('offline',listener);channel.close();instance.unsubscribe();instance.listeners.clear();};}catch(e){setError(e instanceof Error?e.message:String(e));}return()=>{alive=false;cleanup();};},[mode]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer);},[]);
 const run=async(task:()=>Promise<unknown>)=>{try{await task();setError('');return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}};
 if(!engine?.snapshot)return <main className="boot"><h1>FIELDLINE</h1><p>{error||'Opening your fleet…'}</p>{error&&<a href="?mode=demo">Open demo instead</a>}</main>;
 const live=operational(new Date(now));const model=engine.model;const commands=engine.snapshot.commands;const conflicts=commands.filter(c=>c.status==='conflict');
 const sync=mode==='demo'?engine.paused?`Demo · ${commands.length} queued`:commands.length?`Demo · ${commands.length} pending`:'Local demo saved':!navigator.onLine?'Offline · saved locally':engine.connected&&commands.length===0?'Synced':`${commands.length} queued · ${engine.connected?'connected':'connecting'}`;
 const props={model,engine,run,openPump:setPumpId,now};
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="?mode=demo">FIELDLINE<Wrench size={27}/></a><nav>{NAV.map(({id,label,icon:Icon})=><button aria-current={page===id?'page':undefined} className={page===id?'active':''} key={id} onClick={()=>setPage(id)}><Icon size={22}/>{label}</button>)}</nav><div className="sidebar-footer"><strong>{mode==='demo'?'Demo fleet':'Connected fleet'}</strong><span>{sync}</span></div></aside>
 <div className="workspace"><header className="topbar"><div><strong>Fleet 1</strong><span>Live operational shift: {live.shift==='day'?'Day':'Night'} · {live.date}</span></div><div className="topbar-actions"><button className="sync-button" onClick={()=>{setSettings(true);setActor(engine.snapshot.actor);}}>{mode==='demo'||engine.connected?<CloudCheck size={18}/>:<WifiOff size={18}/>}<span>{sync}</span></button><button className="settings-button" onClick={()=>{setSettings(true);setActor(engine.snapshot.actor);}}><Settings size={20}/><span>Settings</span></button></div></header>
 {conflicts.length>0&&<button className="conflict-banner" onClick={()=>setSettings(true)}><AlertTriangle size={19}/>{conflicts.length} conflict{conflicts.length!==1?'s':''} — newer data kept. Review saved changes.</button>}
 {engine.error&&<p className="connection-warning" role="status">{engine.error}</p>}
 <main>{page==='spread'?<Spread {...props} goHours={()=>setPage('hours')}/>:page==='hours'?<Hours {...props}/>:page==='work'?<Work {...props}/>:<Records {...props}/>}</main></div>
 <nav className="mobile-nav">{NAV.map(({id,label,icon:Icon})=><button aria-current={page===id?'page':undefined} className={page===id?'active':''} key={id} onClick={()=>setPage(id)}><Icon size={22}/><span>{label}</span></button>)}</nav>
 {pumpId&&<PumpDrawer {...props} pumpId={pumpId} onClose={()=>setPumpId(null)}/>}
 {settings&&<Modal title="Operator & sync" onClose={()=>setSettings(false)}><p className="mode-notice">{mode==='demo'?'Demo mode. All changes stay in this browser; no production writes.':'Firebase mode. Changes sync to the configured fleet namespace.'}</p><form onSubmit={e=>{e.preventDefault();void run(()=>engine.actor(actor));}}><Field label="Operator name"><input required value={actor} onChange={e=>setActor(e.target.value)}/></Field><button className="primary">Save operator name</button></form><h3>Connection</h3><p>{sync}</p><div className="button-row"><button onClick={()=>run(()=>engine.flush())}>Retry sync</button>{mode==='demo'&&<><button aria-pressed={engine.paused} onClick={()=>{engine.paused=!engine.paused;engine.notify();if(!engine.paused)void engine.flush();}}>{engine.paused?'Resume demo sync':'Pause demo sync'}</button><button onClick={()=>run(()=>engine.simulateConflict())}>Simulate newer server revision</button></>}</div><p className="muted">To evaluate a conflict: pause demo sync, edit an existing reading or pump, then simulate a newer server revision.</p><h3>Saved outbox ({commands.length})</h3>{commands.map(c=><article className="queue-item" key={c.id}><strong>{c.action} · {c.status}</strong><p>{c.error||'Safely stored, waiting to sync.'}</p><small>{new Date(c.at).toLocaleString()} · {c.actor}</small><div className="button-row"><button onClick={()=>download(`fieldline-change-${c.id}.json`,JSON.stringify(c,null,2))}>Export saved change</button>{c.status==='conflict'&&<button onClick={()=>{if(confirm('Discard this retained change? Export it first if you need a copy. Dependent changes may also need review.'))void run(()=>engine.discard(c.id));}}>Discard after review</button>}</div></article>)}
 <h3>Backend mode</h3><div className="button-row"><a className="button" href="?mode=demo">Open demo</a>{configured?<a className="button" href="?mode=firebase">Open Firebase fleet</a>:<p>Firebase not configured. See fieldline/.env.example.</p>}</div><p className="muted">Mode and fleet have separate storage. Configure a dedicated Firebase project; the old Fleet 1 namespace is never modified.</p></Modal>}
 {error&&<div className="toast" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
 </div>;
}
