import { readdir,writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root=new URL('../dist/',import.meta.url);
const assets=(await readdir(new URL('assets/',root))).map(name=>'/assets/'+name);
const cache='fieldline-'+createHash('sha256').update(assets.join(',')).digest('hex').slice(0,12);
await writeFile(new URL('sw.js',root),`const CACHE=${JSON.stringify(cache)};const SHELL=${JSON.stringify(['/', '/index.html','/manifest.webmanifest','/icon.svg',...assets])};
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('fieldline-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).catch(()=>caches.match('/index.html')));return;}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));});
`);
console.log('Offline shell generated:',assets.length,'bundled assets.');
